# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [1]:
import numpy as np




### 2. Print the NUMPY version and the configuration.


In [2]:
print(np.__version__)
np.show_config()


2.0.2
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [3]:
import numpy as np

a1 = np.random.rand(2, 3, 5)
a2 = np.random.randn(2, 3, 5)
a3 = np.random.random((2, 3, 5))



### 4. Print a.


In [6]:
import numpy as np

a = np.random.rand(2, 3, 5)
a = np.random.randn(2, 3, 5)
a = np.random.random((2, 3, 5))
print(a)


[[[0.50389389 0.31231461 0.15478206 0.3605355  0.52016312]
  [0.57285083 0.30812932 0.11014328 0.85319433 0.24314887]
  [0.02883465 0.02401755 0.27362327 0.53744377 0.85861621]]

 [[0.8721035  0.9316195  0.58600207 0.37213662 0.90210372]
  [0.09952176 0.30191812 0.50294809 0.38808554 0.69603324]
  [0.66940903 0.58158291 0.00592262 0.41793666 0.10291674]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [9]:
b = np.ones((5, 2, 3))




### 6. Print b.


In [8]:
print(b)


[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [10]:
print(a.size)
print(b.size)

print(a.size == b.size)


30
30
True



### 8. Are you able to add a and b? Why or why not?


In [13]:
#The shapes are different, you cannot add them without changing the shapes




### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [11]:
b_new = np.transpose(b, (1, 2, 0))

print(a.shape)
print(b_new.shape)

c = a + b_new
print(c)


(2, 3, 5)
(2, 3, 5)
[[[1.50389389 1.31231461 1.15478206 1.3605355  1.52016312]
  [1.57285083 1.30812932 1.11014328 1.85319433 1.24314887]
  [1.02883465 1.02401755 1.27362327 1.53744377 1.85861621]]

 [[1.8721035  1.9316195  1.58600207 1.37213662 1.90210372]
  [1.09952176 1.30191812 1.50294809 1.38808554 1.69603324]
  [1.66940903 1.58158291 1.00592262 1.41793666 1.10291674]]]



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [15]:
#After transpose the shape is compartible
d = a + c
print(d.shape)

(2, 3, 5)



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [20]:
print(a)
print(d)
# d equals 2*a + 1 because c = a + 1 and d = a + c = a + (a + 1).


[[[0.50389389 0.31231461 0.15478206 0.3605355  0.52016312]
  [0.57285083 0.30812932 0.11014328 0.85319433 0.24314887]
  [0.02883465 0.02401755 0.27362327 0.53744377 0.85861621]]

 [[0.8721035  0.9316195  0.58600207 0.37213662 0.90210372]
  [0.09952176 0.30191812 0.50294809 0.38808554 0.69603324]
  [0.66940903 0.58158291 0.00592262 0.41793666 0.10291674]]]
[[[2.00778778 1.62462922 1.30956413 1.72107101 2.04032624]
  [2.14570166 1.61625864 1.22028656 2.70638867 1.48629773]
  [1.05766929 1.0480351  1.54724653 2.07488754 2.71723242]]

 [[2.744207   2.86323899 2.17200413 1.74427324 2.80420744]
  [1.19904351 1.60383625 2.00589617 1.77617109 2.39206647]
  [2.33881807 2.16316583 1.01184524 1.83587333 1.20583347]]]



### 12. Multiply a and c. Assign the result to e.


In [17]:
e = a * c
print(e)


[[[0.75780294 0.40985503 0.17873955 0.49052135 0.79073279]
  [0.90100891 0.403073   0.12227482 1.5811349  0.30227024]
  [0.02966608 0.0245944  0.34849296 0.82628958 1.595838  ]]

 [[1.63266802 1.79953439 0.92940049 0.51062228 1.71589484]
  [0.10942634 0.39307268 0.75590486 0.53869593 1.1804955 ]
  [1.11751749 0.9198216  0.0059577  0.59260772 0.11350859]]]




### 13. Does e equal to a? Why or why not?


In [19]:
# No, because e = a * (a + 1) = a**2 + a, which is not equal to a.





### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [21]:
d_max = d.max()
d_min = d.min()
d_mean = d.mean()




### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [22]:
f = np.empty((2, 3, 5))





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [23]:
f = np.empty(d.shape)

for a in range(d.shape[0]):
    for b in range(d.shape[1]):
        for c in range(d.shape[2]):
            if d[a][b][c] == d_min:
                f[a][b][c] = 0
            elif d[a][b][c] == d_max:
                f[a][b][c] = 100
            elif d[a][b][c] == d_mean:
                f[a][b][c] = 50
            elif d_min < d[a][b][c] < d_mean:
                f[a][b][c] = 25
            elif d_mean < d[a][b][c] < d_max:
                f[a][b][c] = 75






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [24]:
print(d)
print(f)


[[[2.00778778 1.62462922 1.30956413 1.72107101 2.04032624]
  [2.14570166 1.61625864 1.22028656 2.70638867 1.48629773]
  [1.05766929 1.0480351  1.54724653 2.07488754 2.71723242]]

 [[2.744207   2.86323899 2.17200413 1.74427324 2.80420744]
  [1.19904351 1.60383625 2.00589617 1.77617109 2.39206647]
  [2.33881807 2.16316583 1.01184524 1.83587333 1.20583347]]]
[[[ 75.  25.  25.  25.  75.]
  [ 75.  25.  25.  75.  25.]
  [ 25.  25.  25.  75.  75.]]

 [[ 75. 100.  75.  25.  75.]
  [ 25.  25.  75.  25.  75.]
  [ 75.  75.   0.  25.  25.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [25]:
f = np.empty(d.shape, dtype=object)

for a in range(d.shape[0]):
    for b in range(d.shape[1]):
        for c in range(d.shape[2]):
            if d[a][b][c] == d_min:
                f[a][b][c] = "A"
            elif d[a][b][c] == d_max:
                f[a][b][c] = "E"
            elif d[a][b][c] == d_mean:
                f[a][b][c] = "C"
            elif d_min < d[a][b][c] < d_mean:
                f[a][b][c] = "B"
            elif d_mean < d[a][b][c] < d_max:
                f[a][b][c] = "D"

print(f)

[[['D' 'B' 'B' 'B' 'D']
  ['D' 'B' 'B' 'D' 'B']
  ['B' 'B' 'B' 'D' 'D']]

 [['D' 'E' 'D' 'B' 'D']
  ['B' 'B' 'D' 'B' 'D']
  ['D' 'D' 'A' 'B' 'B']]]
